### ISSUE TITLE
Error with no output on Windows 11

### ISSUE THREAD

**Issue by danielhuvr** [kubaszostak/pdf-to-jpg#1]
Not have any success using the bat drag and drop. Getting a few errors, see below:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/111465625/201367855-38b36725-6917-439b-b9b3-d9180f5b7612.png">

**Comment by alfinwilliam** [comment]
Try to rename the source pdf file name to a simpler name like "a.pdf". Worked for me.

**Comment by KubaSzostak** [comment]
Having the problematic PDF would help to solve the issue. Could you provide at least PDF file name?

**Comment by danielhuvr** [comment]
I think the shorter naming worked for me, but don't want to leave this lingering.
